//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LastFMSync.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LastFMSync.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;recenttracks&quot;:{&quot;@attr&quot;:{&quot;page&quot;:&quot;1&quot;,&quot;perPage&quot;:&quot;25&quot;,&quot;user&quot;:&quot;aluhadora&quot;,&quot;total&quot;:&quot;6927&quot;,&quot;totalPages&quot;:&quot;278&quot;},&quot;track&quot;:[{&quot;artist&quot;:{&quot;mbid&quot;:&quot;28503ab7-8bf2-4666-a7bd-2644bfc7cb1d&quot;,&quot;#text&quot;:&quot;Dream Theater&quot;},&quot;album&quot;:{&quot;mbid&quot;:&quot;&quot;,&quot;#text&quot;:&quot;Octavarium (U.S. Version)&quot;},&quot;image&quot;:[{&quot;size&quot;:&quot;small&quot;,&quot;#text&quot;:&quot;https:\/\/lastfm-img2.akamaized.net\/i\/u\/34s\/0ededc95372c4be38bd79b3dd01546c1.jpg&quot;},{&quot;size&quot;:&quot;medium&quot;,&quot;#text&quot;:&quot;https:\/\/lastfm-img2.akamaized.net\/i\/u\/64s\/0ededc95372c4be38bd79b3dd01546c1.jpg&quot;},{&quot;size&quot;:&quot;large&quot;,&quot;#text&quot;:&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestResponse {
            get {
                return ResourceManager.GetString("TestResponse", resourceCulture);
            }
        }
    }
}
